function result = VolFunc4ParamCross(alpha, i, j, T, a, b, c, d)
Talpha = T(alpha);
Ti = T(i-1);
Tj = T(j-1);

result = Talpha*c^2 + (-2*Ti*Tj*a^2*b^2 - Ti*a^2*b - 2*Ti*a*b^2*d - ...
    Tj*a^2*b - 2*Tj*a*b^2*d - a^2 - 2*a*b*d - 2*b^2*d^2 - ...
    4*b*c*(Ti*a*b*exp(Tj*b) + Tj*a*b*exp(Ti*b) + a*exp(Ti*b) + a*exp(Tj*b) ...
    + b*d*exp(Ti*b) + b*d*exp(Tj*b)) + (4*b*c*(-Talpha*a*b*exp(Ti*b) - ...
    Talpha*a*b*exp(Tj*b) + Ti*a*b*exp(Tj*b) + Tj*a*b*exp(Ti*b) + ...
    a*exp(Ti*b) + a*exp(Tj*b) + b*d*exp(Ti*b) + b*d*exp(Tj*b)) + ...
    (2*Talpha^2*a^2*b^2 - 2*Talpha*Ti*a^2*b^2 - 2*Talpha*Tj*a^2*b^2 - ...
    2*Talpha*a^2*b - 4*Talpha*a*b^2*d + 2*Ti*Tj*a^2*b^2 + ...
    Ti*a^2*b + 2*Ti*a*b^2*d + Tj*a^2*b + 2*Tj*a*b^2*d + a^2 + ...
    2*a*b*d + 2*b^2*d^2)*exp(Talpha*b))*exp(Talpha*b))*...
    exp(-b*(Ti + Tj))/(4*b^3);